# Generated by Django 5.2 on 2025-05-29 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registro', '0001_initial'),
        ('mandados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandado',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mandado',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandados', to='login_registro.usuario'),
        ),
        migrations.AlterField(
            model_name='mandado',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repartos', to='login_registro.usuario'),
        ),
    ]
