sonar.projectKey=DiegoLorga_Turbo_mandado
sonar.organization=diegolorga
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.python.version=3.10

# Excluir carpetas innecesarias del análisis
sonar.exclusions=**/migrations/**, **/__pycache__/**, **/venv/**, **/env/**, **/static/**

# Cuando tengas pruebas, activas esto:
# sonar.coverageReportPaths=coverage.xml
